// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQdiFokGGlEyWz62Qf23p62HavO2vaZs',
    appId: '1:16771840661:web:f9f22c5854ffc77b7ff99c',
    messagingSenderId: '16771840661',
    projectId: 'briefdaily',
    authDomain: 'briefdaily.firebaseapp.com',
    storageBucket: 'briefdaily.firebasestorage.app',
    measurementId: 'G-TB2EK6L3WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqCPtlAUgq8OlkR-GJhDB1N1oCCi6iioQ',
    appId: '1:16771840661:android:b9e75ff96c6acb597ff99c',
    messagingSenderId: '16771840661',
    projectId: 'briefdaily',
    storageBucket: 'briefdaily.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6ujmNRFr1lGvkAttvDJbj8tCEeQ4Vk8',
    appId: '1:16771840661:ios:f669c85e786991d47ff99c',
    messagingSenderId: '16771840661',
    projectId: 'briefdaily',
    storageBucket: 'briefdaily.firebasestorage.app',
    iosBundleId: 'com.example.briefdaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6ujmNRFr1lGvkAttvDJbj8tCEeQ4Vk8',
    appId: '1:16771840661:ios:f669c85e786991d47ff99c',
    messagingSenderId: '16771840661',
    projectId: 'briefdaily',
    storageBucket: 'briefdaily.firebasestorage.app',
    iosBundleId: 'com.example.briefdaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPQdiFokGGlEyWz62Qf23p62HavO2vaZs',
    appId: '1:16771840661:web:528592f7075ee6d37ff99c',
    messagingSenderId: '16771840661',
    projectId: 'briefdaily',
    authDomain: 'briefdaily.firebaseapp.com',
    storageBucket: 'briefdaily.firebasestorage.app',
    measurementId: 'G-8QK4VBRLW8',
  );
}
